### Pertemuan 4 - Data Online

In [63]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split



In [4]:
dataset =  pd.read_csv("C:/Users/LABKOM/Downloads/5210411135/data/Data.csv")
dataset

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [26]:
label = dataset['Purchased']
features = dataset.iloc[:,:3].values

features


array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, nan],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', nan, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [27]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [43]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(features[:,1:3])

features[:,1:3] = imputer.transform(features[:,1:3])
features

array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, 54857.142857142855],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', 33.714285714285715, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [45]:
lbenc = LabelEncoder()
features[:,0] = lbenc.fit_transform(features[:,0])

features[:,0]
features

array([[1, 34.0, 92000.0],
       [2, 22.0, 25000.0],
       [0, 31.0, 74000.0],
       [2, 29.0, 54857.142857142855],
       [0, 55.0, 98000.0],
       [1, 24.0, 30000.0],
       [2, 28.0, 40000.0],
       [1, 33.714285714285715, 60000.0],
       [0, 51.0, 89000.0],
       [1, 44.0, 78000.0],
       [2, 21.0, 20000.0],
       [0, 25.0, 30000.0],
       [1, 33.0, 45000.0],
       [1, 42.0, 65000.0],
       [2, 33.0, 22000.0]], dtype=object)

In [47]:
label = lbenc.fit_transform(label)
label

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0], dtype=int64)

In [66]:
x_train, x_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=0)
dimensi = f'dimensi x_train\t: {x_train.shape}\ndimensi x_test\t: {x_test.shape}\ndimensi y_train\t: {y_train.shape}\ndimensi y_test\t: {y_test.shape}\n'

print(dimensi)

dimensi x_train	: (12, 3)
dimensi x_test	: (3, 3)
dimensi y_train	: (12,)
dimensi y_test	: (3,)



In [67]:
sc_x = StandardScaler()

x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

x_train

array([[ 0.00000000e+00,  1.13100526e+00,  8.68162753e-01],
       [ 1.41421356e+00, -7.99435932e-02, -1.31570762e+00],
       [-1.41421356e+00,  2.34195411e+00,  1.64811646e+00],
       [-1.41421356e+00, -3.00116112e-01,  7.12172013e-01],
       [ 0.00000000e+00,  9.10832742e-01,  3.61192846e-01],
       [ 1.41421356e+00, -1.40097871e+00, -1.39370299e+00],
       [ 0.00000000e+00, -1.31055071e-03,  1.66204420e-01],
       [-1.41421356e+00, -9.60633669e-01, -1.00372614e+00],
       [ 1.41421356e+00, -5.20288631e-01, -3.43551036e-02],
       [ 0.00000000e+00,  3.01426663e-02,  1.41413035e+00],
       [ 0.00000000e+00, -1.07071993e+00, -1.00372614e+00],
       [ 0.00000000e+00, -7.99435932e-02, -4.18760858e-01]])